[Core] Make `ManagerInterface.identifier` static
TheFoundryVisionmongers/OpenAssetIO pull request #125
Opened 2021-12-03 15:41 UTC by foundrytom

It doesn't make much sense to allow the manager's identifier to vary. It has to be consistent with the one reported by the ManagerPlugin. Having this be an instance method makes having a single source of truth a little ugly to no tangible benefit.

Leaving the host side, as it makes more sense to be an instance method, as an application may have different modes served from the same binary (eg: PLE).

Considered making this a read-only property, but keeping it as a method for symmetry with `HostInterface` (which has to be a method in c++).

2021-12-03 20:30 UTC, feltech requested changes

2021-12-03 20:30 UTC, feltech commented on python/openassetio/managerAPI/ManagerInterface.py
> -    def identifier(self):
[fix] `Examples.dox` needs updating

2021-12-07 10:50 UTC, foundrytom commented on python/openassetio/managerAPI/ManagerInterface.py
> -    def identifier(self):
Good catch, thanks! Fixed [here](https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/125/commits/d7f45bd639b5653fce4468ce049bd8f321a37e5c).

2021-12-07 10:52 UTC, feltech approved these changes
LGTM squash and merge when ready

2021-12-07 11:56 UTC, merged